# -*- coding: utf-8 -*-
"""Analises_embarque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwVtbNKP2pYdYd9IRgUaFLSvgoorBLX4
"""

# CÓDIGO 01 - PARA A ANALISE DE SENTIMENTOS ESTE CÓDIGO DEVE SER EXECUTADO PRIMEIRO
# ########################################################################################################
# Este código tem como objetivo  a Análise de Sentimentos
# Importa as Módulos do Python para a Análise e estabelece regras lexicas, através de dicionários de emojis
# O Modelo gerado de comentarios inéditos
# Utiliza  técnicas de PLN  e Machine Learning
# Importação dos Módulos do Python
# #####################################################################################################


# instalação de pacotes
!pip install
!pip install nltk
!pip install emoji
!python -m spacy download pt_core_news_sm


import nltk
import spacy
nltk.download('stopwords')
nltk.download('punkt')
nlp = spacy.load("pt_core_news_sm")



import os
import re
import pandas as pd
import emoji
from collections import Counter
from wordcloud import WordCloud
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Esta linha foi incluída para ajustes caso a chamada os spacy
# não funcione corretamente

try:
    nlp = spacy.load("pt_core_news_sm")
except:
    os.system("python -m spacy download pt_core_news_sm")
    nlp = spacy.load("pt_core_news_sm")

# DADOS DE TREINO

negativos = pd.read_csv("500_negativos.csv")
neutros   = pd.read_csv("500_neutros.csv")
positivos = pd.read_csv("500_positivos.csv")

negativos["sentimento"] = "negativo"
neutros["sentimento"]   = "neutro"
positivos["sentimento"] = "positivo"


# Emojis rotulados

emojis_rotulados = pd.read_excel("emojis_rotulados.xlsx")
emojis_rotulados.columns = emojis_rotulados.columns.str.strip()
emojis_rotulados = emojis_rotulados[["comentario","sentimento"]]


# Corpus de Treino (dados de publicacao com tema relacionado)

comentarios = pd.concat([negativos, neutros, positivos, emojis_rotulados], ignore_index=True)
comentarios = comentarios[["comentario","sentimento"]]
comentarios["sentimento"] = comentarios["sentimento"].astype(str).str.strip().str.lower()


# pré-processamento dos dados, preparo para análise PLN

def limpar_comentarios(texto):
    if not isinstance(texto, str):
        return ""
    texto = texto.lower().strip()
    texto = re.sub(r'@\w+', '', texto)
    texto = re.sub(r'http\S+|www\S+', '', texto)
    texto = re.sub(r'#', '', texto)
    lista_emojis = emoji.distinct_emoji_list(texto)
    doc = nlp(texto)
    palavras = []
    for token in doc:
        if (not token.is_stop or token.text in ["não","nunca","jamais","sem"]) and not token.is_punct:
            palavras.append(token.lemma_)
    palavras.extend(["EMOJI_" + e for e in lista_emojis])
    return " ".join(palavras)

comentarios["comentario_limpo"] = comentarios["comentario"].apply(limpar_comentarios)
comentarios = comentarios.dropna(subset=["comentario_limpo","sentimento"])
comentarios = comentarios[comentarios["comentario_limpo"].str.strip() != ""]
comentarios = comentarios.drop_duplicates(subset=["comentario_limpo"])

print("\nDistribuição das classes no treino:")
print(comentarios["sentimento"].value_counts())


# Análise de frequência Treino

todas_palavras = " ".join(comentarios["comentario_limpo"]).split()
frequencia = Counter(todas_palavras)
top10 = pd.DataFrame(frequencia.most_common(10), columns=["palavra","frequencia"])
plt.figure(figsize=(8,5))
plt.bar(top10["palavra"], top10["frequencia"])
plt.title("Top 10 termos (base de treino)")
plt.show()

# Nuvem de palavras  (TREINO)

def gerar_nuvem(df, sentimento, titulo, cor_mapa):
    texto_unico = " ".join(df[df["sentimento"] == sentimento]["comentario_limpo"])
    if texto_unico.strip():
        nuvem = WordCloud(width=800, height=400, background_color='white',
                          colormap=cor_mapa, max_words=100).generate(texto_unico)
        plt.figure(figsize=(10,5))
        plt.imshow(nuvem, interpolation='bilinear')
        plt.title(f"Nuvem de Palavras - {titulo} (treino)", fontsize=16)
        plt.axis("off")
        plt.show()

gerar_nuvem(comentarios, "positivo", "Positivas", "Greens")
gerar_nuvem(comentarios, "negativo", "Negativas", "Reds")


# TREINAMENTO DO MODELO

X = comentarios["comentario_limpo"]
y = comentarios["sentimento"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
"""
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.9, sublinear_tf=True)),
    ("model", LogisticRegression(max_iter=1000))
])
"""
# MODELO MULTINOMIA NAIVE BAYES
# Configurado para capturar unigramas e bigramas
# com ajuste para melhorar o desempenho do modelo

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,2), # bigramas
        min_df=2,
        max_df=0.9,
        sublinear_tf=True
    )),
    ("model", MultinomialNB())
])

#Treinando o modelo

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

print("\nACCURACY:", accuracy_score(y_test, y_pred))
print("\nRELATÓRIO COMPLETO:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de Confusão (treino vs teste)")
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.show()


# === ANÁLISE DE EMOÇÕES (LÉXICO) - FUNÇÃO AUXILIAR ===

# Dicionário de emoções com palavras-chave em português (lemas)
lexico_emocoes = {
    "alegria": ["feliz", "alegre", "contentamente", "bom", "ótimo", "maravilhoso", "adorar", "adoro", "amo", "amor", "divertido", "excelente"],
    "tristeza": ["triste", "chateado", "deprimido", "ruim", "péssimo", "horrível", "melancólico", "decepcionado", "lamentável"],
    "raiva": ["raiva", "irritado", "ódio", "odiar", "péssimo", "horrível", "nojo", "revoltado", "bravo", "fúria"],
    "medo": ["medo", "assustado", "preocupado", "ansioso", "aterrorizado", "temer", "receio"],
    "surpresa": ["surpreso", "impressionado", "incrível", "inesperado", "espantado", "admirado"],
    "amor": ["amor", "adoro", "apaixonado", "carinho", "afeto", "paixão", "romântico"],
    "neutralidade": ["neutro", "normal", "comum", "regular", "indiferente"]
}

def detectar_emocoes(texto_limpo):
    """
    Recebe um texto já limpo (com lemas) e retorna um dicionário com a contagem
    de cada emoção encontrada no texto.
    """
    if not isinstance(texto_limpo, str):
        return {}
    palavras = texto_limpo.split()
    contagem = {emocao: 0 for emocao in lexico_emocoes}
    for palavra in palavras:
        for emocao, palavras_chave in lexico_emocoes.items():
            if palavra in palavras_chave:
                contagem[emocao] += 1

    contagem = {k: v for k, v in contagem.items() if v > 0}
    return contagem


# PARTE COMPLEMENTAR: ANALISAR 'comments_embarque.xlsx' COM O MODELO

# Carregar o novo arquivo Excel
novo_df = pd.read_excel("comments_embarque.xlsx")

# Coluna de Interesse
coluna_texto = "Comente"

if coluna_texto not in novo_df.columns:
    raise KeyError(f"Coluna '{coluna_texto}' não encontrada. Colunas disponíveis: {list(novo_df.columns)}")

# Aplicar a MESMA limpeza
novo_df["comentario_limpo"] = novo_df[coluna_texto].apply(limpar_comentarios)
novo_df = novo_df[novo_df["comentario_limpo"].str.strip() != ""]
novo_df = novo_df.dropna(subset=["comentario_limpo"])

# Classificar os comentários (sentimento)
novo_df["sentimento_previsto"] = pipeline.predict(novo_df["comentario_limpo"])


# QUANTIDADE E PERCENTUAL DOS SENTIMENTOS PREVISTOS

contagem = novo_df["sentimento_previsto"].value_counts()
percentual = novo_df["sentimento_previsto"].value_counts(normalize=True) * 100

resultados = pd.DataFrame({
    "Quantidade": contagem,
    "Percentual (%)": percentual.round(2)
})

print("\n=== RESULTADOS DA CLASSIFICAÇÃO (comments_embarque.xlsx) ===")
print(resultados)

# Gráfico de barras com percentuais
plt.figure(figsize=(6,4))
ax = sns.barplot(x=resultados.index, y=resultados["Percentual (%)"],
                 order=["positivo", "neutro", "negativo"],
                 palette=["green", "gray", "red"])
plt.title("Percentual de Sentimentos Previstos")
plt.xlabel("Sentimento")
plt.ylabel("Percentual (%)")
for i, p in enumerate(ax.patches):
    ax.annotate(f'{p.get_height():.1f}%',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom')
plt.show()

# Gráfico de contagem original
plt.figure(figsize=(6,4))
sns.countplot(data=novo_df, x="sentimento_previsto", order=["positivo", "neutro", "negativo"],
              palette=["green", "gray", "red"])
plt.title("Quantidade de Sentimentos Previstos")
plt.xlabel("Sentimento")
plt.ylabel("Número de comentários")
plt.show()


# ANÁLISE DE EMOÇÕES ENCONTRADAS (GRÁFICO DE BARRAS)

novo_df["emocoes"] = novo_df["comentario_limpo"].apply(detectar_emocoes)

# Agrupa todas as contagens de emoções em um único Counter
contagem_emocoes_total = Counter()
for emocoes_dict in novo_df["emocoes"]:
    if emocoes_dict:
        contagem_emocoes_total.update(emocoes_dict)

# Exibe as emoções encontradas
if contagem_emocoes_total:
    print("\n=== EMOÇÕES ENCONTRADAS NOS COMENTÁRIOS ===")
    for emocao, qtd in contagem_emocoes_total.most_common():
        print(f"{emocao.capitalize()}: {qtd} ocorrências")

    # Gráfico de barras das emoções
    df_emocoes = pd.DataFrame(contagem_emocoes_total.most_common(), columns=["Emoção", "Frequência"])
    plt.figure(figsize=(8,5))
    sns.barplot(data=df_emocoes, x="Emoção", y="Frequência", palette="viridis")
    plt.title("Emoções Encontradas nos Comentários")
    plt.xlabel("Emoção")
    plt.ylabel("Número de menções")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
else:
    print("\nNenhuma emoção identificada com o léxico atual.")


# NUVENS DE PALAVRAS PARA CADA SENTIMENTO PREVISTO

def gerar_nuvem_novo(df, sentimento, titulo, cor_mapa):
    textos = df[df["sentimento_previsto"] == sentimento]["comentario_limpo"]
    if textos.empty:
        print(f"Nenhum comentário previsto como '{sentimento}' – nuvem ignorada.")
        return
    texto_unico = " ".join(textos)
    nuvem = WordCloud(width=800, height=400, background_color='white',
                      colormap=cor_mapa, max_words=100).generate(texto_unico)
    plt.figure(figsize=(10,5))
    plt.imshow(nuvem, interpolation='bilinear')
    plt.title(f"Nuvem de palavras – {titulo} (previsto no novo arquivo)", fontsize=16)
    plt.axis("off")
    plt.show()

gerar_nuvem_novo(novo_df, "positivo", "Positivas", "Greens")
gerar_nuvem_novo(novo_df, "neutro",   "Neutras",   "Blues")
gerar_nuvem_novo(novo_df, "negativo", "Negativas", "Reds")


# SALVAR RESULTADOS COM AS PREVISÕES E EMOÇÕES

# Converte a coluna de dicionários para string antes de salvar (opcional)
novo_df["emocoes_str"] = novo_df["emocoes"].apply(str)
novo_df.to_excel("comments_embarque_classificado.xlsx", index=False)
print("\nArquivo com previsões e emoções salvo como 'comments_embarque_classificado.xlsx'")

# Extração de Categorias baseada em Regras Keyword Matching
# O Objetivo deste código é extrair temas dos comentários através de técnicas de NLP
# Um dicionario de termos foi colocado e através dele extraiu-se as palavras

# CATEGORIAS (REGRAS)


categorias_keywords = {
    "Radar": [
        "radar", "meteorologia", "clima", "tempestade", "nuvens", "previsão"
    ],
    "Segurança de Voo": [
        "segurança", "incidente", "acidente", "queda", "colisão",
        "procedimento", "emergência", "falha", "risco", "aterrissagem forçada"
    ],
    "Aeroportos": [
        "aeroporto", "terminal", "check-in", "embarque", "desembarque",
        "fila", "esteira", "bagagem", "alfândega"
    ],
    "Roteiro": [
        "viagem", "destino", "roteiro", "turismo", "passagem",
        "hotel", "conexão", "escala", "itinerário"
    ],
    "Aviação": [
        "avião", "aeronave", "voo", "piloto", "copiloto",
        "turbina", "turbulência", "cabine", "cockpit", "hangar"
    ],
    "Bem-estar": [
        "cansaço", "estresse", "saúde", "bem-estar", "sono",
        "ansiedade", "fadiga", "descanso"
    ],
    "Carreira": [
        "carreira", "emprego", "vaga", "profissão", "curso",
        "formação", "treinamento", "salário", "promoção"
    ],
    "Você Sabia": [
        "você sabia", "curiosidade", "sabia que", "dica", "informação",
        "história", "fato"
    ]
}


# FUNÇÃO DE CLASSIFICAÇÃO

def detectar_categorias(texto):
    texto = str(texto).lower()
    categorias_encontradas = []
    for categoria, palavras in categorias_keywords.items():
        for palavra in palavras:
            if palavra in texto:
                categorias_encontradas.append(categoria)
                break
    if len(categorias_encontradas) == 0:
        return ["Sem Categoria"]
    return categorias_encontradas


# APLICA NO DATASET (treino e novo_banco)

comentarios["categorias"] = comentarios["comentario_limpo"].apply(detectar_categorias)
novo_banco["categorias"] = novo_banco["comentario_limpo"].apply(detectar_categorias)


# EXPLODIR (PARA ANÁLISE DE FREQUÊNCIA)

df_cat = comentarios.explode("categorias")


# FREQUÊNCIA (QUANTIDADE) DE CATEGORIAS

freq_cat = df_cat["categorias"].value_counts()

# Gráfico de barras horizontal com QUANTIDADE (sem grid)
plt.figure(figsize=(10,5))
freq_cat.sort_values().plot(kind="barh", color="skyblue")
plt.title("Distribuição de Categorias dos Comentários (Quantidade)")
plt.xlabel("Número de comentários")
plt.ylabel("Categoria")
plt.grid(False)
plt.tight_layout()
plt.show()


# PERCENTUAL DAS CATEGORIAS (gráfico de barras com rótulos, sem grid)

total_categorias = freq_cat.sum()
freq_cat_pct = (freq_cat / total_categorias) * 100
freq_cat_pct_sorted = freq_cat_pct.sort_values()

plt.figure(figsize=(10,5))
bars = plt.barh(freq_cat_pct_sorted.index, freq_cat_pct_sorted.values, color="lightgreen")
plt.title("Categorias dos Comentários (Percentual)")
plt.xlabel("Percentual (%)")
plt.ylabel("Categoria")
plt.grid(False)

# Adiciona rótulos de percentual nas barras
for bar, pct in zip(bars, freq_cat_pct_sorted.values):
    plt.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
             f"{pct:.1f}%", va='center')

plt.tight_layout()
plt.show()



# Extração de Emojis Únicos

import nltk
import spacy
import pandas as pd
import matplotlib.pyplot as plt

nltk.download('stopwords')
nlp = spacy.load("pt_core_news_sm")


# =========================
# IMPORTAÇÃO DOS DADOS
# =========================
df_embarque = pd.read_excel('comments_embarque.xlsx')

novo_banco = df_embarque[['Comente']].copy()
novo_banco.columns = ['comentario']


# =========================
# PRÉ-PROCESSAMENTO
# =========================
novo_banco['comentario_limpo'] = novo_banco['comentario'].apply(limpar_comentarios)

# verificar quantidade antes e depois
print("Total de comentários antes da limpeza:", len(novo_banco))

novo_banco = novo_banco.dropna(subset=['comentario_limpo'])

print("Total de comentários após limpeza:", len(novo_banco))


# =========================
# CLASSIFICAÇÃO DE SENTIMENTO
# =========================
# OBS: pipeline já deve estar treinado anteriormente com fit()

novo_banco['Sentimento'] = pipeline.predict(
    novo_banco['comentario_limpo']
)


# =========================
# VISUALIZAÇÃO INICIAL
# =========================
print("\nAmostra dos dados classificados:\n")
print(novo_banco[['comentario', 'Sentimento']].head(20))

print("\nDistribuição dos sentimentos:\n")
print(novo_banco['Sentimento'].value_counts())


# =========================
# GRÁFICO DE BARRAS (PRINCIPAL)
# =========================
ordem = ['negativo', 'neutro', 'positivo']
polaridades = novo_banco['Sentimento'].value_counts().reindex(ordem)

plt.figure(figsize=(8,5))
polaridades.plot(kind='bar')

plt.title('Distribuição dos Sentimentos - Revista Embarque')
plt.xlabel('Sentimento')
plt.ylabel('Quantidade')
plt.xticks(rotation=0)

# adicionar valores nas barras
for i, v in enumerate(polaridades.values):
    if pd.notnull(v):
        plt.text(i, v + 1, str(int(v)), ha='center')

plt.show()



# GRÁFICO DE PIZZA

polaridades_pizza = novo_banco['Sentimento'].value_counts()

plt.figure(figsize=(8,8))
plt.pie(
    polaridades_pizza,
    labels=polaridades_pizza.index,
    autopct='%1.1f%%'
)

plt.title('Distribuição das Polaridades (%)')
plt.show()


# Extraíndo os emojis do comentários comentários da Embarque
# Emojis ùnicos
# este código está ligado ao campo novo banco

!pip install emoji

from enum import unique

import emoji

somente_emojis = []
somente_textos = []
for p in novo_banco['comentario'].fillna(''):

    p = str(p)

    # extrai emojis
    lista_emojis = emoji.distinct_emoji_list(p)
    somente_emojis.append(lista_emojis)

    # remove emojis do texto
    texto_sem_emoji = emoji.replace_emoji(p, replace='')
    somente_textos.append(texto_sem_emoji.strip())
    #print(lista_emojis)
    #print(texto_sem_emoji)

    emojis_unicos = set()

for lista in somente_emojis:
    emojis_unicos.update(lista)

print(emojis_unicos)

banco_emojis = pd.DataFrame(emojis_unicos, columns=['emoji'])

# Extrai os valores únicos como um array NumPy
valores_unicos = banco_emojis['emoji'].unique()
#print(valores_unicos)  # Saída: ['A' 'B' 'C']

# Para contar quantos valores únicos existem, use nunique()
contagem = banco_emojis['emoji'].nunique()
#print(contagem)  # Saída: 3

to_excel = banco_emojis.to_excel('emojis.xlsx', index=True)

# ANALISE EXPLORATÓRIA SOMENTE COMENTARIOS EMBARQUE

# eMOJIS

# FREQUÊNCIA

import pandas as pd
import numpy as np
import re
import emoji
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from collections import Counter

# Stopwords
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

stop_words = set(stopwords.words('portuguese'))


#  CARREGAR BASE

df = pd.read_excel('comments_embarque.xlsx')

print(f"Dataset: {df.shape[0]} linhas e {df.shape[1]} colunas")


# LIMPEZA INICIAL
# ================================
df['Comente'] = df['Comente'].fillna('').astype(str)


#  EXTRAIR EMOJIS (ANTES DE LIMPAR)

def extrair_emojis(texto):
    return [c for c in texto if c in emoji.EMOJI_DATA]

df['emojis'] = df['Comente'].apply(extrair_emojis)


#  LIMPAR TEXTO (SEM EMOJI)

def limpar_texto(texto):
    texto = re.sub(r'@\w+', '', texto)  # remove @
    texto = re.sub(r'http\S+|www\S+', '', texto)  # remove links
    texto = re.sub(r'#\w+', '', texto)  # remove hashtags
    texto = re.sub(r'[^\w\s]', '', texto)  # remove pontuação
    texto = texto.lower()
    texto = texto.strip()
    return texto

df['texto_limpo'] = df['Comente'].apply(limpar_texto)


# MÉTRICAS BÁSICAS

df['tamanho_texto'] = df['texto_limpo'].str.len()
df['qtd_palavras'] = df['texto_limpo'].apply(lambda x: len(x.split()))
df['qtd_emojis'] = df['emojis'].apply(len)


#  ESTATÍSTICAS

print("\n--- Estatísticas ---")
print(df[['tamanho_texto', 'qtd_palavras', 'qtd_emojis']].describe())


# TOKENIZAÇÃO (SEM NLTK - ROBUSTO)

tokens = []

for texto in df['texto_limpo']:
    palavras = re.findall(r'\b\w+\b', texto)
    palavras = [p for p in palavras if p not in stop_words and len(p) > 2]
    tokens.extend(palavras)

#  FREQUÊNCIA DE PALAVRAS

freq_palavras = Counter(tokens)
top_20 = freq_palavras.most_common(20)

df_top = pd.DataFrame(top_20, columns=['Palavra', 'Frequência'])

print("\n--- Top 20 Palavras ---")
print(df_top)


#  GRÁFICO - TOP PALAVRAS

plt.figure(figsize=(10,5))
sns.barplot(data=df_top, x='Frequência', y='Palavra')
plt.title("Top 20 Palavras")
plt.show()


#  NUVEM DE PALAVRAS

if len(tokens) > 0:
    texto_wordcloud = " ".join(tokens)

    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(texto_wordcloud)

    plt.figure(figsize=(10,5))
    plt.imshow(wordcloud)
    plt.axis('off')
    plt.title("Nuvem de Palavras")
    plt.show()
else:
    print("⚠️ Sem palavras suficientes para WordCloud")


#  ANÁLISE DE EMOJIS

todos_emojis = [e for lista in df['emojis'] for e in lista]

freq_emojis = Counter(todos_emojis)
top_emojis = freq_emojis.most_common(20)

df_emoji = pd.DataFrame(top_emojis, columns=['Emoji', 'Frequência'])

print("\n--- Top Emojis ---")
print(df_emoji)


#  GRÁFICO EMOJIS

if not df_emoji.empty:
    plt.figure(figsize=(10,5))
    sns.barplot(data=df_emoji, x='Frequência', y='Emoji')
    plt.title("Top Emojis")
    plt.show()
else:
    print("⚠️ Nenhum emoji encontrado")

#  SIGNIFICADO DOS EMOJIS

def significado_emoji(e):
    return emoji.demojize(e, language='pt')

df_emoji['Significado'] = df_emoji['Emoji'].apply(significado_emoji)

print("\n--- Emojis com significado ---")
print(df_emoji)


#  LISTA DE EMOJIS ÚNICOS

emojis_unicos = list(set(todos_emojis))

df_emojis_unicos = pd.DataFrame(emojis_unicos, columns=['Emoji'])

# adicionar significado
df_emojis_unicos['Significado'] = df_emojis_unicos['Emoji'].apply(significado_emoji)

print("\n--- Emojis Únicos ---")
print(df_emojis_unicos)

print(f"\nTotal de emojis únicos: {len(emojis_unicos)}")


#  BOXPLOT

plt.figure()
sns.boxplot(data=df[['qtd_palavras']])
plt.title("Boxplot - Quantidade de Palavras")
plt.show()

plt.figure()
sns.boxplot(data=df[['tamanho_texto']])
plt.title("Boxplot - Tamanho do Texto")
plt.show()


#  DISTRIBUIÇÃO

plt.figure()
sns.histplot(df['qtd_palavras'], kde=True)
plt.title("Distribuição - Quantidade de Palavras")
plt.show()

plt.figure()
sns.histplot(df['tamanho_texto'], kde=True)
plt.title("Distribuição - Tamanho do Texto")
plt.show()

