# -*- coding: utf-8 -*-
"""processamento_insta - Copia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VR5otR1cvL8crcIFSYrNta6dVRiJy-Cx
"""



# Parte 1 - Explorar a préprocessar métricas do Instagram, extraídos do Dashboard do Metabusiness
# Analise Exploratória dos dados Quantitativos extraídos do Metabusiness do Instagram
# Este arquivo tem a finalidade de explorar os dados captados

#importação dos módulos para o processamento dos dados
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

#importando arquivos
#importacao_dados-instagram
insta = pd.read_excel('de_2017_2025.xlsx')

#Analisar o conteúdo da tabela
insta.head()



#verificação os tipos de variáveis
insta.info()

insta.tail(6)

#remoção as 4 últimas colunas do banco insta
#remoção as 4 ultimas linha do banco que são NAN
insta = insta.iloc[:-4]

insta.tail(4)

#Tarefas antes de iniciar os graficos
"""tranformando identificadores das contas em inteiros
Identificação da publicação  1678 non-null   float64
Identificação da conta       1678 non-null   float64"""

insta['Identificação da publicação']=insta['Identificação da publicação'].astype(int)
insta['Identificação da conta']=insta['Identificação da conta'].astype(int)

insta.head()

# Verificando tipos de variáveis
insta['Horário de publicação'].info()

insta.info()

# Conversão de object para data
#data_n = pd.to_datetime(insta['Horário de publicação'], dayfirst=True, errors='coerce')
data_n = pd.to_datetime(insta['Horário de publicação'])

# Criar uma nova coluna no formato dia/mês/ano
insta['data_formatada'] = data_n.dt.strftime('%d/%m/%Y')

insta.columns

data_n.info()

insta.tail()



# Preenchimento dos campos NAN(vazios) neste caso para contagem por zeros, Substituir NAN por zeros:
# Estes Campos estavam vazios nos anos anteriores
"""
Curtidas                     1679 non-null   float64
Compartilhamentos            1679 non-null   float64
Seguimentos                  823 non-null    float64
Comentários                  1679 non-null   float64
Salvamentos                  1679 non-null   float64
Alcance                      732 non-null    float64
Visualizações                198 non-null    float64"""

insta[['Curtidas','Compartilhamentos','Seguimentos','Comentários','Salvamentos','Alcance','Visualizações']]=insta[['Curtidas','Compartilhamentos','Seguimentos','Comentários','Salvamentos','Alcance','Visualizações']].fillna(0)



#Tipo de publicação
#removeu-se o final com str.replace('do instagram')
insta['Tipo de publicação']=insta['Tipo de publicação'].str.replace('do Instagram', '',regex=False)
insta['Tipo de publicação'] = insta['Tipo de publicação'].str.replace('do Instagram', '', regex=False)

# Valores únicos da coluna
print(insta['Tipo de publicação'].unique())

# Quantidade de linhas que não terminam com 'do instagram'
print((~insta['Tipo de publicação'].str.endswith('do instagram', na=False)).sum())

#Remove dos tipos de publicação a menção "do instagram", fica mais fácil identificar os tipos únicos de publicação analisados

diferentes = insta[~insta['Tipo de publicação'].str.endswith('do instagram', na=False)]
print(diferentes)

# Verifica se existe, na coluna "Tipo de publicação", algum valor diferente de "do Instagram

existe_diferente = (~insta['Tipo de publicação'].str.endswith('do Instagram', na=False)).any()
print(existe_diferente)

# # Verifica se existe, na coluna "Tipo de publicação", algum valor diferente de "do Instagram e cria instacia insta_deferentes


insta_diferentes = insta[~insta['Tipo de publicação'].str.endswith('do Instagram', na=False)]
print(insta_diferentes)

# Remover link e seção do instagram de publicação e deixar shortcode
# A ideia aqui é caso fosse necessário gerar uma nova tabel consolidade com os links caso fosse necessário acessar


insta['shortcode'] = insta['Link permanente'].str.extract(r'/p/([^/]+)/')

# Tabela com shortcode (link da publicação) para acesso da publicação


insta['shortcode']

insta.columns

#criar uma coluna ano
# Criar uma coluna com o ano
insta['Ano'] = pd.to_datetime(insta['data_formatada'], format='%d/%m/%Y', errors='coerce').dt.year

insta['Ano']

#criando nova tabela de dados
insta_ = insta[['shortcode', 'Identificação da conta', 'Identificação da publicação', 'Curtidas', 'Compartilhamentos', 'Seguimentos', 'Comentários', 'Salvamentos', 'Alcance', 'Visualizações', 'Ano']]

# Nova tabela com o shorcode

insta_

# Gráfico de Dispersão - Matriz de dispersão
# verificação de possíveis relações entre as variáveis

import seaborn as sns
import matplotlib.pyplot as plt

# Selecionar apenas as variáveis numéricas de interesse
df_disp = insta_[['Visualizações', 'Alcance', 'Curtidas', 'Comentários']]

# Remover possíveis valores extremos (opcional, mas recomendado)
df_disp = df_disp[df_disp['Visualizações'] > 0]

# Criar a matriz de dispersão
sns.pairplot(df_disp)

# Título geral (opcional)
plt.suptitle('Matriz de Dispersão - Métricas do Instagram', y=1.02)

# Exibir
plt.show()

# Gráfico de distribuição das métricas - histograma
# Mostrar como os valores das métricas estão distribuídos

import matplotlib.pyplot as plt
import numpy as np

# Selecionar variáveis
df_dist = insta_[['Visualizações', 'Alcance', 'Curtidas', 'Comentários']]

# Aplicar log para melhorar distribuição
df_dist_log = np.log1p(df_dist)

# Criar gráfico
plt.figure(figsize=(10,6))

for coluna in df_dist_log.columns:
    plt.hist(df_dist_log[coluna], bins=50, alpha=0.5, label=coluna)

# Configurações
plt.xlabel('Valores (escala log)')
plt.ylabel('Frequência')
plt.title('Distribuição das Métricas do Instagram')
plt.legend()

# =========================
# REMOVER CAIXA (ESTILO LIMPO)
# =========================

ax = plt.gca()

# Remove bordas superior e direita
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Mantém apenas eixo X e Y
ax.spines['left'].set_visible(True)
ax.spines['bottom'].set_visible(True)

# Ajustar espessura dos eixos
ax.spines['left'].set_linewidth(1)
ax.spines['bottom'].set_linewidth(1)

# Remover grade (opcional)
ax.grid(False)

# Layout final
plt.tight_layout()
plt.show()



# Explorando dados da Embarque

#Totalização de todos os anos
import matplotlib.pyplot as plt

# Criando o gráfico de barras
plt.bar(insta_['Ano'], insta_['Curtidas'], color='skyblue')
plt.bar(insta_['Ano'], insta_['Comentários'], color='red')
# Títulos e rótulos
plt.title('Curtidas por ano')
plt.xlabel('Anos')
plt.ylabel('Curtidas')

# Exibir o gráfico
plt.show()

# Totais de curtidas e comentários

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import matplotlib.font_manager

for f in matplotlib.font_manager.findSystemFonts(fontpaths=None, fontext='ttf'):
    print(matplotlib.font_manager.FontProperties(fname=f).get_name())

# Configurando a fonte global
rcParams['font.family'] = 'Arial'

# Criar a largura das barras
bar_width = 0.4
anos = insta_['Ano'].unique()
anos.sort()

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar as curtidas e comentários por ano
curtidas_por_ano = insta_.groupby('Ano')['Curtidas'].sum()
comentarios_por_ano = insta_.groupby('Ano')['Comentários'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10,6))
plt.bar(r1, curtidas_por_ano, color='skyblue', width=bar_width, label='Curtidas')
plt.bar(r2, comentarios_por_ano, color='red', width=bar_width, label='Comentários')

# Adicionar os valores em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], curtidas_por_ano.iloc[i] + 50, int(curtidas_por_ano.iloc[i]), ha='center', fontsize=12)
    plt.text(r2[i], comentarios_por_ano.iloc[i] + 50, int(comentarios_por_ano.iloc[i]), ha='center', fontsize=12)

# Ajustar o eixo x
plt.xlabel('Ano')
plt.ylabel('Quantidade')
plt.title('Total de Curtidas e Comentários por Ano')
#plt.xticks([r + bar_width/2 for r in r1], anos)
plt.xticks([r + bar_width/2 for r in r1], anos, fontsize=12)
plt.yticks(fontsize=12)
plt.legend(fontsize=12)

# Adicionar legenda
plt.legend(fontsize=12)

# Exibir o gráfico
plt.tight_layout()
# Salvando o gráfico como imagem PNG
plt.savefig('curtidas_comentarios_ano.png', dpi=300, bbox_inches='tight')
plt.show()

# Totais Curtidas e Comentários

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import matplotlib.font_manager


# Criar a largura das barras
bar_width = 0.4
anos = insta_['Ano'].unique()
anos.sort()

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar as curtidas e comentários por ano
curtidas_por_ano = insta_.groupby('Ano')['Curtidas'].sum()
comentarios_por_ano = insta_.groupby('Ano')['Comentários'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10,6))
plt.bar(r1, curtidas_por_ano, color='skyblue', width=bar_width, label='Curtidas')
plt.bar(r2, comentarios_por_ano, color='red', width=bar_width, label='Comentários')

# Adicionar os valores em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], curtidas_por_ano.iloc[i] + 50, int(curtidas_por_ano.iloc[i]), ha='center', fontsize=12)
    plt.text(r2[i], comentarios_por_ano.iloc[i] + 50, int(comentarios_por_ano.iloc[i]), ha='center', fontsize=12)

# Ajustar o eixo x
plt.xlabel('Ano')
plt.ylabel('Quantidade')
plt.title('Total de Curtidas e Comentários por Ano')
plt.xticks([r + bar_width/2 for r in r1], anos, fontsize=12)
plt.yticks(fontsize=12)
plt.legend(fontsize=12)

# Adicionar legenda
plt.legend(fontsize=12)

# Exibir o gráfico
plt.tight_layout()
# Salvando o gráfico como imagem PNG
plt.savefig('curtidas_comentarios_ano.png', dpi=300, bbox_inches='tight')
# plt.show() # Remova o comentário se quiser exibir o gráfico em uma janela

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams

# Configurar a fonte global como Arial 11
rcParams['font.family'] = 'Arial'
rcParams['font.size'] = 11

# Filtrar os dados para remover ano zero
insta_filtrado = insta_[insta_['Ano'] > 0]

# Criar a largura das barras
bar_width = 0.4
anos = sorted(insta_filtrado['Ano'].unique())

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar os totais por ano
curtidas_por_ano = insta_filtrado.groupby('Ano')['Curtidas'].sum()
comentarios_por_ano = insta_filtrado.groupby('Ano')['Comentários'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10, 6))
plt.bar(r1, curtidas_por_ano, color='skyblue', width=bar_width, label='Curtidas')
plt.bar(r2, comentarios_por_ano, color='red', width=bar_width, label='Comentários')

# Adicionar os totais em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], curtidas_por_ano.iloc[i] + curtidas_por_ano.max() * 0.01, int(curtidas_por_ano.iloc[i]),
             ha='center', fontsize=11)
    plt.text(r2[i], comentarios_por_ano.iloc[i] + comentarios_por_ano.max() * 0.01, int(comentarios_por_ano.iloc[i]),
             ha='center', fontsize=11)

# Configurar os rótulos dos eixos
plt.xlabel('Ano', fontsize=11)
plt.ylabel('Quantidade', fontsize=11)

# Configurar os ticks do eixo X
plt.xticks([r + bar_width / 2 for r in r1], anos, fontsize=11)

# Configurar os ticks do eixo Y
plt.yticks(fontsize=11)

# Adicionar legenda
plt.legend(fontsize=11)

# Remover a moldura (bordas) deixando só os eixos X e Y
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(True)
ax.spines['bottom'].set_visible(True)
ax.spines['left'].set_linewidth(1)
ax.spines['bottom'].set_linewidth(1)

# Layout final
plt.tight_layout()
plt.savefig('curtidas_comentarios_ano.png', dpi=300, bbox_inches='tight')
plt.show()

# Estatísticas descritivas das variáveis Curtidas e Comentários

# Agrupando por Ano
estatisticas = insta_.groupby('Ano')[['Curtidas', 'Comentários']].agg(['mean', 'median', 'std'])

# Arredondando para 2 casas decimais
estatisticas = estatisticas.round(2)

print(estatisticas)



# Exportando arquivo

estatisticas.to_csv('estatisticas_por_ano.csv', index=True)

# Médias do total de comentários e curtidas
print(insta_[['Curtidas', 'Comentários']].agg(['mean', 'median', 'std']))

# Resumo Estatístico
estatisticas = insta_.groupby('Ano')[['Curtidas', 'Comentários']].agg(['mean', 'median', 'std'])

# Tabela Resumo Estatístico
estatisticas.style.format("{:.2f}").set_caption("Resumo Estatístico: Curtidas e Comentários por Ano")

import matplotlib.pyplot as plt

# Calcula a média por ano
medias = insta_.groupby('Ano')[['Curtidas', 'Comentários']].mean()

# Plotando
medias.plot(kind='bar', figsize=(8,6), color=['skyblue', 'salmon'])
plt.title('Média de Curtidas e Comentários por Ano')
plt.ylabel('Média')
plt.xlabel('Ano')
plt.tight_layout()
plt.show()

# Gráfico Box-plot
# Distribuição de um conjunto de dados numéricos

plt.figure(figsize=(10,6))
insta_.boxplot(column=['Curtidas', 'Comentários'])
plt.title('Distribuição de Curtidas e Comentários')
plt.ylabel('Quantidade')
plt.show()

# Mapa de Calor com as metricas dos comentários e Cutidas

import seaborn as sns

# Resumo estatístico por ano
estatisticas_plot = insta_.groupby('Ano')[['Curtidas', 'Comentários']].agg(['mean', 'median', 'std'])

plt.figure(figsize=(10,6))
sns.heatmap(estatisticas_plot.T, annot=True, fmt=".1f", cmap="YlGnBu")
plt.title('Resumo Estatístico por Ano - Curtidas e Comentários')
plt.show()

# Dados Brutos relacionados à Alcance e visualização

insta.head()

insta_.to_excel('insta_final.xlsx', index=False)

# Explorando as variáveis Alcance e Visualizações

import numpy as np
import matplotlib.pyplot as plt

# Criar a largura das barras
bar_width = 0.4
anos = sorted(insta_['Ano'].unique())

# Garantir que "anos" esteja como uma lista simples
anos = list(anos)

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar os totais por ano
alcance_por_ano = insta_.groupby('Ano')['Alcance'].sum()
visualizacoes_por_ano = insta_.groupby('Ano')['Visualizações'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10, 6))
plt.bar(r1, alcance_por_ano, color='skyblue', width=bar_width, label='Alcance')
plt.bar(r2, visualizacoes_por_ano, color='red', width=bar_width, label='Visualizações')

# Adicionar os valores em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], alcance_por_ano.iloc[i] + 50, int(alcance_por_ano.iloc[i]), ha='center', fontsize=10)
    plt.text(r2[i], visualizacoes_por_ano.iloc[i] + 50, int(visualizacoes_por_ano.iloc[i]), ha='center', fontsize=10)

# Ajustar os ticks do eixo x
plt.xlabel('Ano', fontsize=14)
plt.ylabel('Quantidade', fontsize=14)
plt.title('Total de Usuários Alcançados e Visualizações por Ano', fontsize=16)

# Ajustar as labels do eixo x
plt.xticks([r + bar_width / 2 for r in r1], anos, fontsize=12)

plt.yticks(fontsize=12)
plt.legend(fontsize=12)

# Melhor layout
plt.tight_layout()

# Salvar a imagem
plt.savefig('alcance_visualizacoes_ano.png', dpi=300, bbox_inches='tight')

# Exibir o gráfico
plt.show()

# Explorando as variáveis Alcance e Visualizações

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from matplotlib import rcParams

# Configurando a fonte global
rcParams['font.family'] = 'Arial'

# Filtrar os dados para remover ano zero
insta_filtrado = insta_[insta_['Ano'] > 0]

# Criar a largura das barras
bar_width = 0.4
anos = sorted(insta_filtrado['Ano'].unique())

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar os totais por ano
alcance_por_ano = insta_filtrado.groupby('Ano')['Alcance'].sum()
visualizacoes_por_ano = insta_filtrado.groupby('Ano')['Visualizações'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10, 6))
plt.bar(r1, alcance_por_ano, color='skyblue', width=bar_width, label='Alcance')
plt.bar(r2, visualizacoes_por_ano, color='red', width=bar_width, label='Visualizações')

# Adicionar os valores em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], alcance_por_ano.iloc[i] + 50, int(alcance_por_ano.iloc[i]), ha='center', fontsize=12)
    plt.text(r2[i], visualizacoes_por_ano.iloc[i] + 50, int(visualizacoes_por_ano.iloc[i]), ha='center', fontsize=12)

# Ajustar os ticks do eixo x
plt.xlabel('Ano', fontsize=14)
plt.ylabel('Quantidade', fontsize=14)
plt.title('Total de Usuários Alcançados e Visualizações por Ano', fontsize=16)

# Ajustar as labels do eixo x
plt.xticks([r + bar_width / 2 for r in r1], anos, fontsize=12)

plt.yticks(fontsize=12)
plt.legend(fontsize=12)

plt.tight_layout()
plt.savefig('alcance_visualizacoes_ano.png', dpi=300, bbox_inches='tight')
plt.show()



# Testando remoção de Grid superior e Esquerdo

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams

# Configurar a fonte global como Arial 11
rcParams['font.family'] = 'Arial'
rcParams['font.size'] = 11

# Filtrar os dados para remover ano zero
insta_filtrado = insta_[insta_['Ano'] > 0]

# Criar a largura das barras
bar_width = 0.4
anos = sorted(insta_filtrado['Ano'].unique())

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar os totais por ano
alcance_por_ano = insta_filtrado.groupby('Ano')['Alcance'].sum()
visualizacoes_por_ano = insta_filtrado.groupby('Ano')['Visualizações'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10, 6))
plt.bar(r1, alcance_por_ano, color='skyblue', width=bar_width, label='Alcance')
plt.bar(r2, visualizacoes_por_ano, color='red', width=bar_width, label='Visualizações')

# Configurar os rótulos dos eixos
plt.xlabel('Ano', fontsize=11)
plt.ylabel('Quantidade', fontsize=11)

# Configurar os ticks do eixo X
plt.xticks([r + bar_width / 2 for r in r1], anos, fontsize=11)

# Configurar os ticks do eixo Y
plt.yticks(fontsize=11)

# Adicionar legenda
plt.legend(fontsize=11)

# Remover a caixa (bordas) do gráfico, deixando só os eixos X e Y
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(True)
ax.spines['bottom'].set_visible(True)

# Opcional: deixar as linhas dos eixos um pouco mais grossas (se quiser)
ax.spines['left'].set_linewidth(1)
ax.spines['bottom'].set_linewidth(1)

# Layout final
plt.tight_layout()
plt.savefig('alcance_visualizacoes_ano.png', dpi=300, bbox_inches='tight')
plt.show()

# Explorando alcance e visualizações
# Grafico padrão para entrega

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams

# Configurar a fonte global como Arial 11
rcParams['font.family'] = 'Arial'
rcParams['font.size'] = 11

# Filtrar os dados para remover ano zero
insta_filtrado = insta_[insta_['Ano'] > 0]

# Criar a largura das barras
bar_width = 0.4
anos = sorted(insta_filtrado['Ano'].unique())

# Posicionar as barras
r1 = np.arange(len(anos))
r2 = [x + bar_width for x in r1]

# Somar os totais por ano
alcance_por_ano = insta_filtrado.groupby('Ano')['Alcance'].sum()
visualizacoes_por_ano = insta_filtrado.groupby('Ano')['Visualizações'].sum()

# Criar o gráfico de barras lado a lado
plt.figure(figsize=(10, 6))
plt.bar(r1, alcance_por_ano, color='skyblue', width=bar_width, label='Alcance')
plt.bar(r2, visualizacoes_por_ano, color='red', width=bar_width, label='Visualizações')

# Adicionar os totais em cima de cada barra
for i in range(len(anos)):
    plt.text(r1[i], alcance_por_ano.iloc[i] + alcance_por_ano.max() * 0.01, int(alcance_por_ano.iloc[i]),
             ha='center', fontsize=11)
    plt.text(r2[i], visualizacoes_por_ano.iloc[i] + visualizacoes_por_ano.max() * 0.01, int(visualizacoes_por_ano.iloc[i]),
             ha='center', fontsize=11)

# Configurar os rótulos dos eixos
plt.xlabel('Ano', fontsize=11)
plt.ylabel('Quantidade', fontsize=11)

# Configurar os ticks do eixo X
plt.xticks([r + bar_width / 2 for r in r1], anos, fontsize=11)

# Configurar os ticks do eixo Y
plt.yticks(fontsize=11)

# Adicionar legenda
plt.legend(fontsize=11)

# Remover a moldura (bordas) deixando só os eixos X e Y
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(True)
ax.spines['bottom'].set_visible(True)
ax.spines['left'].set_linewidth(1)
ax.spines['bottom'].set_linewidth(1)

# Layout final
plt.tight_layout()
plt.savefig('alcance_visualizacoes_ano.png', dpi=300, bbox_inches='tight')
plt.show()

insta.tail(100)

# estatísticas de Alcance e Visualizações

# Agrupando por Ano
estatisticas_visualizacoes = insta_.groupby('Ano')[['Alcance', 'Visualizações']].agg(['mean', 'median', 'std'])

# Arredondando para 2 casas decimais
estatisticas_visualizacoes = estatisticas_visualizacoes.round(2)

print(estatisticas_visualizacoes)

# Exportando dados transfomados

estatisticas_visualizacoes.to_csv('estatisticas_visualizacoes.csv', index=True)